name: cffconvert

on:
  push:
    paths:
      - CITATION.cff

jobs:
  convert:
    name: "convert"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Convert CITATION.cff to Zenodo metadata format
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--infile ./CITATION.cff --format zenodo --outfile .zenodo.json"

      - name: Commit and push Zenodo metadata
        run: |
          git config --global user.name 'cffconvert GitHub Action'
          git config --global user.email 'cffconvert@users.noreply.github.com'
          git add .zenodo.json
          git commit -m "Automated update of Zenodo metadata"
          git push
