name: cffconvert

on:
  push:
    paths:
      - CITATION.cff
permissions:
  contents: write
jobs:
  convert:
    name: "convert citations"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v3

      - name: Convert CITATION.cff to Zenodo metadata format
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--infile ./CITATION.cff --format zenodo --outfile .zenodo.json"

      - name: Commit and create a Pull Request with the Zenodo file
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ":robot: Update .zenodo.json"
          committer: "'github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          title: "[auto] Update .zenodo.json"
